{% set name = "xsarsea" %}
{% set version = "1.7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xsarsea-{{ version }}.tar.gz
  sha256: 7a0b5aaf1f23ddd2e53a535c878c30d593a34b289aebae921c889c1090304770

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - xarray
    - opencv
    - importlib-resources
    - fsspec
    - aiohttp
    - numba
    - scipy
    - pyyaml
    - typer
    - netcdf4
    - matplotlib-base
    - xrft

test:
  imports:
    - xsarsea
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/umr-lops/xsarsea
  summary: cmod, detrend, and others sar processing tools over ocean
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze
    - vincelhx
    - Skealz
