{% set name = "xsarsea" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xsarsea-{{ version }}.tar.gz
  sha256: 48e52d42099f3fae498cdb7d272b86f1c8313d736792d98fbd463af55b8041d8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools-scm
    - pip
  run:
    - python
    - numpy
    - xarray
    - opencv
    - importlib-resources
    - fsspec
    - aiohttp
    - numba
    - scipy
    - pyyaml
    - typer
    - netcdf4
    - matplotlib-base
    - xrft

test:
  imports:
    - xsarsea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/umr-lops/xsarsea
  summary: cmod, detrend, and others sar processing tools over ocean
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze
    - vincelhx
    - Skealz
